#!/bin/bash
[[ $- != *i* ]] && return
alias ls='exa'
alias ll='exa -la'
alias l.='exa -d .* --color=auto'
alias c='clear'
alias b='cd ../'
export PS1="\[\e[31m\][\[\e[m\]\[\e[33m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[34m\]\h\[\e[m\] \[\e[35m\]\W\[\e[m\]\[\e[31m\]]\[\e[m\]\\$ "
HISTSIZE= HISTFILESIZE=
set -o vi
function lh() {
    history | grep "$1";
}
upload() {
    curl --progress-bar --upload-file "$1" https://transfer.sh/$(basename $1) | tee /dev/null && echo "";
}
alias upload=upload
